name: 02 - Workflow Events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
        workflow_dispatch:
            
jobs:
    echo:
        runs-on: ubunto-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by a(an) ${{ github.event_name }} event."
